/**:
  ros__parameters:
    base_scan:
      clearing: true
      data_type: LaserScan
      expected_update_rate: 0.4
      marking: true
      max_obstacle_height: 0.4
      min_obstacle_height: 0.08
      observation_persistence: 0.0
    cost_scaling_factor: 10.0
    footprint:
    - - -0.325
      - -0.325
    - - -0.325
      - 0.325
    - - 0.325
      - 0.325
    - - 0.46
      - 0.0
    - - 0.325
      - -0.325
    footprint_padding: 0.01
    global_frame: map
    height: 6.0
    inflation_radius: 0.55
    lethal_cost_threshold: 100
    map_type: voxel
    mark_threshold: 0
    max_obstacle_height: 2.0
    observation_sources: base_scan
    obstacle_range: 2.5
    origin_z: 0.0
    publish_frequency: 1.0
    publish_voxel_map: true
    raytrace_range: 3.0
    resolution: 0.025
    robot_base_frame: base_link
    rolling_window: true
    static_map: false
    transform_tolerance: 0.3
    unknown_threshold: 10
    update_frequency: 5.0
    width: 6.0
    z_resolution: 0.2
    z_voxels: 10
